/**
	* Bibliothèque pour affichage de couleur sur le terminal
	* Source : https://en.wikipedia.org/wiki/ANSI_escape_code
	* Exemple d'utilisation : printf(RED("Test")); 
*/
#ifndef _COLOR_ANSI_H_
	#define _COLOR_ANSI_H_
	/*-------------------------------------*/
	/* Énumération des codes couleurs ANSI */
	/*-------------------------------------*/
	// Normal
	#define COLOR_RESET		"\x1b[0m"
	#define NORMAL_BLACK	"\x1b[30m"
	#define NORMAL_RED		"\x1b[31m"
	#define NORMAL_GREEN	"\x1b[32m"
	#define NORMAL_YELLOW	"\x1b[33m"
	#define NORMAL_BLUE		"\x1b[34m"
	#define NORMAL_MAGENTA	"\x1b[35m"
	#define NORMAL_CYAN		"\x1b[36m"
	#define NORMAL_WHITE	"\x1b[36m"
	// Gras
	#define BOLD_BLACK		"\x1b[1;30m"
	#define BOLD_RED		"\x1b[1;31m"
	#define BOLD_GREEN		"\x1b[1;32m"
	#define BOLD_YELLOW		"\x1b[1;33m"
	#define BOLD_BLUE		"\x1b[1;34m"
	#define BOLD_MAGENTA	"\x1b[1;35m"
	#define BOLD_CYAN		"\x1b[1;36m"
	#define BOLD_WHITE		"\x1b[1;37m"
	// Mince
	#define FAINT_BLACK		"\x1b[2;30m"
	#define FAINT_RED		"\x1b[2;31m"
	#define FAINT_GREEN		"\x1b[2;32m"
	#define FAINT_YELLOW	"\x1b[2;33m"
	#define FAINT_BLUE		"\x1b[2;34m"
	#define FAINT_MAGENTA	"\x1b[2;35m"
	#define FAINT_CYAN		"\x1b[2;36m"
	#define FAINT_WHITE		"\x1b[2;37m"
	// Italique
	#define ITALIC_BLACK	"\x1b[3;30m"
	#define ITALIC_RED		"\x1b[3;31m"
	#define ITALIC_GREEN	"\x1b[3;32m"
	#define ITALIC_YELLOW	"\x1b[3;33m"
	#define ITALIC_BLUE		"\x1b[3;34m"
	#define ITALIC_MAGENTA	"\x1b[3;35m"
	#define ITALIC_CYAN		"\x1b[3;36m"
	#define ITALIC_WHITE	"\x1b[3;37m"
	// Souligné
	#define UNDERLINED_BLACK	"\x1b[4;30m"
	#define UNDERLINED_RED		"\x1b[4;31m"
	#define UNDERLINED_GREEN	"\x1b[4;32m"
	#define UNDERLINED_YELLOW	"\x1b[4;33m"
	#define UNDERLINED_BLUE		"\x1b[4;34m"
	#define UNDERLINED_MAGENTA	"\x1b[4;35m"
	#define UNDERLINED_CYAN		"\x1b[4;36m"
	#define UNDERLINED_WHITE	"\x1b[4;37m"
	// Clignotement lent (150 par minute)
	#define SLOW_BLINK_BLACK	"\x1b[5;30m"
	#define SLOW_BLINK_RED		"\x1b[5;31m"
	#define SLOW_BLINK_GREEN	"\x1b[5;32m"
	#define SLOW_BLINK_YELLOW	"\x1b[5;33m"
	#define SLOW_BLINK_BLUE		"\x1b[5;34m"
	#define SLOW_BLINK_MAGENTA	"\x1b[5;35m"
	#define SLOW_BLINK_CYAN		"\x1b[5;36m"
	#define SLOW_BLINK_WHITE	"\x1b[5;37m"
	// Clignotement rapide (+150 par minute)
	#define FAST_BLACK			"\x1b[6;30m"
	#define FAST_RED			"\x1b[6;31m"
	#define FAST_GREEN			"\x1b[6;32m"
	#define FAST_YELLOW			"\x1b[6;33m"
	#define FAST_BLUE			"\x1b[6;34m"
	#define FAST_MAGENTA		"\x1b[6;35m"
	#define FAST_CYAN			"\x1b[6;36m"
	#define FAST_WHITE			"\x1b[6;37m"
	// Échange des couleurs premier plan et de l'arrière plan
	#define SWAPPED_BLACK		"\x1b[7;30m"
	#define SWAPPED_RED			"\x1b[7;31m"
	#define SWAPPED_GREEN		"\x1b[7;32m"
	#define SWAPPED_YELLOW		"\x1b[7;33m"
	#define SWAPPED_BLUE		"\x1b[7;34m"
	#define SWAPPED_MAGENTA		"\x1b[7;35m"
	#define SWAPPED_CYAN		"\x1b[7;36m"
	#define SWAPPED_WHITE		"\x1b[7;37m"
	// Dissimule ou cache
	#define CONCEALED_BLACK		"\x1b[8;30m"
	#define CONCEALED_RED		"\x1b[8;31m"
	#define CONCEALED_GREEN		"\x1b[8;32m"
	#define CONCEALED_YELLOW	"\x1b[8;33m"
	#define CONCEALED_BLUE		"\x1b[8;34m"
	#define CONCEALED_MAGENTA	"\x1b[8;35m"
	#define CONCEALED_CYAN		"\x1b[8;36m"
	#define CONCEALED_WHITE		"\x1b[8;37m"
	// Barré
	#define STRIKED_BLACK		"\x1b[9;30m"
	#define STRIKED_RED			"\x1b[9;31m"
	#define STRIKED_GREEN		"\x1b[9;32m"
	#define STRIKED_YELLOW		"\x1b[9;33m"
	#define STRIKED_BLUE		"\x1b[9;34m"
	#define STRIKED_MAGENTA		"\x1b[9;35m"
	#define STRIKED_CYAN		"\x1b[9;36m"
	#define STRIKED_WHITE		"\x1b[9;37m"
	// Par défault
	#define DEFAULT_BLACK		"\x1b[10;30m"
	#define DEFAULT_RED			"\x1b[10;31m"
	#define DEFAULT_GREEN		"\x1b[10;32m"
	#define DEFAULT_YELLOW		"\x1b[10;33m"
	#define DEFAULT_BLUE		"\x1b[10;34m"
	#define DEFAULT_MAGENTA		"\x1b[10;35m"
	#define DEFAULT_CYAN		"\x1b[10;36m"
	#define DEFAULT_WHITE		"\x1b[10;37m"
	// Arrière plan
	#define BACKGROUN_BLACK		"\x1b[40m"
	#define BACKGROUND_RED		"\x1b[41m"
	#define BACKGROUND_GREEN	"\x1b[42m"
	#define BACKGROUND_YELLOW	"\x1b[43m"
	#define BACKGROUND_BLUE		"\x1b[44m"
	#define BACKGROUND_MAGENTA	"\x1b[45m"
	#define BACKGROUND_CYAN		"\x1b[46m"
	#define BACKGROUND_WHITE	"\x1b[47m"
	/*---------------------------------------*/
	/* Fonctions d'utilisations des couleurs */
	/*---------------------------------------*/
	// Normal
	#define COLOR_NORMAL_BLACK(X)		NORMAL_BLACK X COLOR_RESET
	#define COLOR_NORMAL_RED(X)			NORMAL_RED X COLOR_RESET
	#define COLOR_NORMAL_GREEN(X)		NORMAL_GREEN X COLOR_RESET
	#define COLOR_NORMAL_YELLOW(X)		NORMAL_YELLOW X COLOR_RESET
	#define COLOR_NORMAL_BLUE(X)		NORMAL_BLUE X COLOR_RESET
	#define COLOR_NORMAL_MAGENTA(X)		NORMAL_MAGENTA X COLOR_RESET
	#define COLOR_NORMAL_CYAN(X)		NORMAL_CYAN X COLOR_RESET
	#define COLOR_NORMAL_WHITE(X)		NORMAL_WHITE X COLOR_RESET
	// Gras
	#define COLOR_BOLD_BLACK(X)			BOLD_BLACK X COLOR_RESET
	#define COLOR_BOLD_RED(X)			BOLD_RED X COLOR_RESET
	#define COLOR_BOLD_GREEN(X)			BOLD_GREEN X COLOR_RESET
	#define COLOR_BOLD_YELLOW(X)		BOLD_YELLOW X COLOR_RESET
	#define COLOR_BOLD_BLUE(X)			BOLD_BLUE X COLOR_RESET
	#define COLOR_BOLD_MAGENTA(X)		BOLD_MAGENTA X COLOR_RESET
	#define COLOR_BOLD_CYAN(X)			BOLD_CYAN X COLOR_RESET
	#define COLOR_BOLD_WHITE(X)			BOLD_WHITE X COLOR_RESET
	// Mince
	#define COLOR_FAINT_BLACK(X)		FAINT_BLACK X COLOR_RESET
	#define COLOR_FAINT_RED(X)			FAINT_RED X COLOR_RESET
	#define COLOR_FAINT_GREEN(X)		FAINT_GREEN X COLOR_RESET
	#define COLOR_FAINT_YELLOW(X)		FAINT_YELLOW X COLOR_RESET
	#define COLOR_FAINT_BLUE(X)			FAINT_BLUE X COLOR_RESET
	#define COLOR_FAINT_MAGENTA(X)		FAINT_MAGENTA X COLOR_RESET
	#define COLOR_FAINT_CYAN(X)			FAINT_CYAN X COLOR_RESET
	#define COLOR_FAINT_WHITE(X)		FAINT_WHITE X COLOR_RESET
	// Italique
	#define COLOR_ITALIC_BLACK(X)		ITALIC_BLACK X COLOR_RESET
	#define COLOR_ITALIC_RED(X)			ITALIC_RED X COLOR_RESET
	#define COLOR_ITALIC_GREEN(X)		ITALIC_GREEN X COLOR_RESET
	#define COLOR_ITALIC_YELLOW(X)		ITALIC_YELLOW X COLOR_RESET
	#define COLOR_ITALIC_BLUE(X)		ITALIC_BLUE X COLOR_RESET
	#define COLOR_ITALIC_MAGENTA(X)		ITALIC_MAGENTA X COLOR_RESET
	#define COLOR_ITALIC_CYAN(X)		ITALIC_CYAN X COLOR_RESET
	#define COLOR_ITALIC_WHITE(X)		ITALIC_WHITE X COLOR_RESET
	// Souligné
	#define COLOR_UNDERLINED_BLACK(X)	UNDERLINED_BLACK X COLOR_RESET
	#define COLOR_UNDERLINED_RED(X)		UNDERLINED_RED X COLOR_RESET
	#define COLOR_UNDERLINED_GREEN(X)	UNDERLINED_GREEN X COLOR_RESET
	#define COLOR_UNDERLINED_YELLOW(X)	UNDERLINED_YELLOW X COLOR_RESET
	#define COLOR_UNDERLINED_BLUE(X)	UNDERLINED_BLUE X COLOR_RESET
	#define COLOR_UNDERLINED_MAGENTA(X)	UNDERLINED_MAGENTA X COLOR_RESET
	#define COLOR_UNDERLINED_CYAN(X)	UNDERLINED_CYAN X COLOR_RESET
	#define COLOR_UNDERLINED_WHITE(X)	UNDERLINED_WHITE X COLOR_RESET
	// Clignotement lent (150 par minute)
	#define COLOR_SLOW_BLINK_BLACK(X)	SLOW_BLINK_BLACK X COLOR_RESET
	#define COLOR_SLOW_BLINK_RED(X)		SLOW_BLINK_RED X COLOR_RESET
	#define COLOR_SLOW_BLINK_GREEN(X)	SLOW_BLINK_GREEN X COLOR_RESET
	#define COLOR_SLOW_BLINK_YELLOW(X)	SLOW_BLINK_YELLOW X COLOR_RESET
	#define COLOR_SLOW_BLINK_BLUE(X)	SLOW_BLINK_BLUE X COLOR_RESET
	#define COLOR_SLOW_BLINK_MAGENTA(X)	SLOW_BLINK_MAGENTA X COLOR_RESET
	#define COLOR_SLOW_BLINK_CYAN(X)	SLOW_BLINK_CYAN X COLOR_RESET
	#define COLOR_SLOW_BLINK_WHITE(X)	SLOW_BLINK_WHITE X COLOR_RESET
	// Échange des couleurs premier plan et de l'arrière plan
	#define COLOR_SWAPPED_BLACK(X)		SWAPPED_BLACK X COLOR_RESET
	#define COLOR_SWAPPED_RED(X)		SWAPPED_RED X COLOR_RESET
	#define COLOR_SWAPPED_GREEN(X)		SWAPPED_GREEN X COLOR_RESET
	#define COLOR_SWAPPED_YELLOW(X)		SWAPPED_YELLOW X COLOR_RESET
	#define COLOR_SWAPPED_BLUE(X)		SWAPPED_BLUE X COLOR_RESET
	#define COLOR_SWAPPED_MAGENTA(X)	SWAPPED_MAGENTA X COLOR_RESET
	#define COLOR_SWAPPED_CYAN(X)		SWAPPED_CYAN X COLOR_RESET
	#define COLOR_SWAPPED_WHITE(X)		SWAPPED_WHITE X COLOR_RESET
	// Dissimule ou cache la couleur
	#define COLOR_CONCEALED_BLACK(X)	CONCEALED_BLACK X COLOR_RESET
	#define COLOR_CONCEALED_RED(X)		CONCEALED_RED X COLOR_RESET
	#define COLOR_CONCEALED_GREEN(X)	CONCEALED_GREEN X COLOR_RESET
	#define COLOR_CONCEALED_YELLOW(X)	CONCEALED_YELLOW X COLOR_RESET
	#define COLOR_CONCEALED_BLUE(X)		CONCEALED_BLUE X COLOR_RESET
	#define COLOR_CONCEALED_MAGENTA(X)	CONCEALED_MAGENTA X COLOR_RESET
	#define COLOR_CONCEALED_CYAN(X)		CONCEALED_CYAN X COLOR_RESET
	#define COLOR_CONCEALED_WHITE(X)	CONCEALED_WHITE X COLOR_RESET
	// Barré
	#define COLOR_STRIKED_BLACK(X)		STRIKED_BLACK X COLOR_RESET
	#define COLOR_STRIKED_RED(X)		STRIKED_RED X COLOR_RESET
	#define COLOR_STRIKED_GREEN(X)		STRIKED_GREEN X COLOR_RESET
	#define COLOR_STRIKED_YELLOW(X)		STRIKED_YELLOW X COLOR_RESET
	#define COLOR_STRIKED_BLUE(X)		STRIKED_BLUE X COLOR_RESET
	#define COLOR_STRIKED_MAGENTA(X)	STRIKED_MAGENTA X COLOR_RESET
	#define COLOR_STRIKED_CYAN(X)		STRIKED_CYAN X COLOR_RESET
	#define COLOR_STRIKED_WHITE(X)		STRIKED_WHITE X COLOR_RESET
	// Par défault
	#define COLOR_DEFAULT_BLACK(X)		DEFAULT_BLACK X COLOR_RESET
	#define COLOR_DEFAULT_RED(X)		DEFAULT_RED X COLOR_RESET
	#define COLOR_DEFAULT_GREEN(X)		DEFAULT_GREEN X COLOR_RESET
	#define COLOR_DEFAULT_YELLOW(X)		DEFAULT_YELLOW X COLOR_RESET
	#define COLOR_DEFAULT_BLUE(X)		DEFAULT_BLUE X COLOR_RESET
	#define COLOR_DEFAULT_MAGENTA(X)	DEFAULT_MAGENTA X COLOR_RESET
	#define COLOR_DEFAULT_CYAN(X)		DEFAULT_CYAN X COLOR_RESET
	#define COLOR_DEFAULT_WHITE(X)		DEFAULT_WHITE X COLOR_RESET
	// Arrière plan
	#define COLOR_BACKGROUND_BLACK(X)		BACKGROUND_BLACK X COLOR_RESET
	#define COLOR_BACKGROUND_RED(X)			BACKGROUND_RED X COLOR_RESET
	#define COLOR_BACKGROUND_GREEN(X)		BACKGROUND_GREEN X COLOR_RESET
	#define COLOR_BACKGROUND_YELLOW(X)		BACKGROUND_YELLOW X COLOR_RESET
	#define COLOR_BACKGROUND_BLUE(X)		BACKGROUND_BLUE X COLOR_RESET
	#define COLOR_BACKGROUND_MAGENTA(X)		BACKGROUND_MAGENTA X COLOR_RESET
	#define COLOR_BACKGROUND_CYAN(X)		BACKGROUND_CYAN X COLOR_RESET
	#define COLOR_BACKGROUND_WHITE(X)		BACKGROUND_WHITE X COLOR_RESET
#endif
